sudo: required
notifications:
  email: false
services:
- docker
language: python
python:
- 3.6
git:
  depth: false
script:
- make build
- make push
deploy:
- provider: script
  skip_cleanup: true
  script: bash .travis-deploy.sh
  on:
    branch: master
env:
  global:
  - secure: F+M7q6DHgF5tBoIaSYfX5IoXvRVWQ04vG4bnp7T0fS+HLL3zGqtu+F5jwmAGscC69kYPourgHJtCv86hcieU2ay8+aKBQupu6V2TKFqQ3fenoUjzNHdtSbL7kv+xq3csNhpMq223aNfKI18V4jEjA4tyFSPWNIWR9WFm4b38BHxCpSIgbXgm8H5g7Z1lGtkpusDXqyJYBvPF+HfIr8n9keMhqktd1ZUSxjzdxu+WoGE4sGa41iGwLUejZzSuBOS4mq+hgnJ107rLWKcpaXl0nQYzUe6TYbqrxVmbu+3KvJUYJ2JpewVS/ExBf+6oNQvaMlTJa8vOg42QLSsG+44KAGrs2IUA4G3DpD9uQ9JfcoxydpJh6uCU5dVT92Z+k689h3NqJko7dvF3RK6HW0Vg3SgHh3NKSVhhPP7q8qtlT4WEZ5dma7HornstCIZCAy7X0FAqlcLA+v1+Wkn1q+Z7OOhCHGyfq8TT8fHq3cmepeY2TLPXry0KLHNdQMzoTu3TQYb3mJkyLsC2+IrGF5Xybwv82OEuEjwcd2X2JuRmKm2sLxQ+kAyv3U64EpMOUw7hiylQrJKwN3a2v9Ay+6d2QwaD7cAtdhmA800T9y5uwzhex8S5bN0R5waxPV8uJmDarpzj3152Zv709YZiooyJYS/dXpswBxJLHHQjMrb2A4o=
  - secure: HT2dD2u0buc+QTdhTQ45UKP2EwtsOWw9hmk6tST49hODry7UdqKd6nOKh2AwoqXi0vZotmuDi0kAiiUfmvv8rFTkPySmuP/ebF/oYUOAJsmSxCW5oYnJwEyYF8ONUUExEs6ehs6yFg5p3WtqhUHKlizWFuqIdzv58ABNUYHT5h0NOL7mA/6jacbTKyi/aZS99JVvkwKs7TQA7ifQj/LLdowLT27TPE3avZ02C6S84STXctzE97hdv3aJC0Goek7oM5YxSKH7dIK1L/N+3d10EdJwdpDIsRhQiBZQr4zWDPXtlsg3ETyWicSLmNpCWGwA/4/s9teDykejXdqdU2aqM86cu1+2KIUFdAMZEtEWZd2qwVNcqkvV77SF1bsChdb5OTKQ+jaFA13JkxXosTQl751BNYi3wdcVd3WEK3622pCk45c2aKw7DOQMpoAE+5KSjyzK1vN9KzLzVx4Esh45OHwxALrUfdfVT5TF7O4FbMhsQXktCNY4DaOhhh6sqxPfd25sABOAvL7K1zpVtCdJJCNwyrxrt60LgQUqPAJdOke2ocAww9AtbgxBX/4Z6Usc//VrvfmW1x+ZW3v/qbQRI9+/3TFuCkRkxIt3qBt4NteMYJYIDDKIVSpgX6/kTlbOiurPBnevbMGtIgdGm56a95ROdOIzvSKWvzCH6ASKkPM=
