sudo: required
notifications:
  email: false
services:
- docker
language: python
python:
- 3.6
git:
  depth: false
script:
- make build
- make push
deploy:
- provider: script
  skip_cleanup: true
  script: bash .travis-deploy.sh
  on:
    branch: master
env:
  global:
  - secure: j0pwbm0Sm8zcWUFClyctNb8UhKVgBzU3gBaTCF1oWa7/9OpUfbL6Hyua8/ERaAhST+IBWb6PeRffD4WkY18FatDkxmyk3DcwsqSW55Om69Kipj+Y8KTqAkdTojZO0/tvq3fFgaqAuLc3cchONIZTl8EZPQDWzt+gVvwZanZJOIu/phWryKgc3tovA2Wwjkf3rtNuMKusbCAlC6IXOOlxQnDiCtjD6Itv4/BhoczJmxzxRHvgY47bTGcot9kTc7dmvH/qnD6E2bqT2cGSjk4vEnImwUwFHe36d5/3qdMgTPepvgLzsWVuM8FKuVoik8KveKeShS39f1pRPYT2rXt9Tu/1my23F+I9urSJW4a+MT0p4FtKCUPwi+fXqE3wX7RIEzWtEeJT4aI3cw8qrFGrGpNIKi+Vd97KphFdVURsHnR7nuPUuvcfdqrSE4YyUR7Xm+hzqnSd2AilDCNtHX+u9MVqmSogCUBb8dDwafBrZuwNJLSfKyhfHz4Q4F1us07PbNcXI7oEbabA/DAPhMXPMvEFJEKNrN1Hru4qrWCHXKvs7oR1LLps7NtWagfAnPqIN0g7b/sm+me1yJKv2SHC5VLKlv/rfNe0WeD8lZ/dIgcGSSYvRkJoQbQ1eEVHkai+E+u0kxySPRBVR1VaGnRWertosFLi2kgkN0R1ACgVrys=
  - secure: 5sxEwDS0XpRxexxDxjdgWD9eQBMLb9I8K8UCHACvzVmeGQUGqGiY3hV3AFSaNSt4r39botIxSRIEnlXMFrIAfakuvtaBSYqo/wJ8aiIx7EWC+7VghPOLTU1ieObxoDyYZK7TmU46fOQEZWrZAZjcdtT5mMSfzY/uvaiY8BnDNsgmfiv0QaeJnL5BF+w7m5U6CrdC2kw5onaHD83iPhFKsHTL5R2bn3GELyZFwuANQ+DANKZFgUkNIOZaYZRKBqo+elrRCYES7Wtia1pxbHcFghR6uJEkI0vjvIYQ2tAiRRubjQCTsdY2ZIGnt6BFrY7rnFjkz+MZAcEJfNy6wXsdUIXnoXhkplPalxo6nEl42d774SN1FLw9AweGSk4zIrAdWMGGh9QXRfez5mVwereOChPtUJsaUhOQlRmEeob/ONVISfvwBuaIz2QAQipyYulK/HJeLr0mc5n3FM/X8mun3SBKU+xmnkOpue1kfvgffI0moeJoSllUn6JAx85OyNVAe+zExAD2V8kQdKGLQ+3MyIMJRCp2T6f4wcg4rGilp93mV3SLeRE0Je1L/Xc+SB08fCSb79QWi906B//QYAcxVMggWYy/6q4wN0EbuXLJ5NjWY9mwQCjoCdMTDb1gMPfiTbB46cb0xl3pds6HIv/BqgbxGWlo9dl3IeB7QtptFFE=
