sudo: required
notifications:
  email: false
services:
- docker
language: python
python:
- 3.6
git:
  depth: false
script:
- make build
- make push
deploy:
- provider: script
  skip_cleanup: true
  script: bash .travis-deploy.sh
  on:
    branch: master
env:
  global:
  - secure: JPncV2OUIU46QhTu8mn9MDkaTiODsq5IvCeAUTG5gisNwx8x4WXXNVvW2HeCL/CKFfGKKkJBD/Ws9ONSBI9/tnwBESOcNDZttdd0l9m+7cB+igWUYQcehMiTxs7EKY9k8ZyYD9VEYpNXxsj4obZ7bIHB3r03BpYq5l98O+ZcVcbO6En9GSfnn2jKuXzuCI4MyeoKwnRO5gOnMJAForFb15RJ4fHVV4hOXGLKGQpf/LTW2v7c4W9PCKH12a6O3ZWLCyr0bJoMWC7TsX8RogiYM0RAzAwMFHfHk5aTLd0+fXE15pbS92P3vDGL5B7z/6fvd2icJsooKNLbJ39+r52tjycfIy8dlaNGmEMNd3BODxhbZZ8t/txDyQpXjXxT8AG8AI8oOxcMnU0lKq+V8jZ+Uby7Ei+i0/8NIAkWNC7xAJ1DsQQuE6aRjmZ+BQ58nHgrWTCwwvCSB5f3Y0HFGG8kznY23CIXHWUAhqSRywGlFbf8DMqTJPVp/pgEACc5cmKFJUGGBdUqrEB0Dennj4bETO+hyUlS7QC0KddBitrYVdfL73nrdP3zUrEE5MOBfQZnXUkaPa4FWqZAPjsaSNvnlVsae90tkmt1xqA8Xos9NbwkAiLKWHCo9VG0vjmOKVKMnID2m5tqAUnSyAcNYv45Exy5pUm6mn144r0djrz4ZRw=
  - secure: jmMddGQwTen7nH+uh4enyx/Am83TFu6zsPQvmD8NNY0tGQrodUlnSOkleDmo3DKpwUYwK66SggMXhjSa1UFawCD9Qbk5J8FSG0PKTOA8F81I0XSZ1N8KkoLU0YEpMMZjGf0dzQ3P9egBP6k4uaTltlGZ2qp1VstbjrvmvgiaJ362wFNiPXvRpB2CZmcWnMq6bPmzZXVgMSpU5xe/n7rdDOfjoerszMbK/UwL1D37m+7dDamFsY/OibM6aPLgvecUGjoLrcHUaYS3tilqMXYhjHIsEEi0TOlsoDPhjlnrEh6afm+w9TTrulIyQSn8t+qOMBC0KuWdxFVw6ebvVZzJwZvaf2t960bn0k7gTg3YGVt6jQkSM7lJ8At2Cku2OPLGpgAi680qK2N98GQA4e+e9I8T6yzw8TvOAqbf9V/TWzajT1ReReEmloGqcvx6PKwkwYh2VoHrX4O7zNe73z7FSL3OpWed0HRJBVVjFremNvEPLEaNR+qS1LsfqosBCDPOCYAbJpUTSGKb1aCSitv2XsQlYiIIXCBcz780s97Y2N3IhiBP19fIWwoM3mcoQhgGruNTijler6nPvA2QCpLrdg/tFVo40/oBAwmbudV1BZKtQ8N5GJYZj3KZ7sWkNaXfoqg7gJJEUHReH/PBeQ+wuULyII6E25ZGyMBjREf5FBo=
